### ISSUE TITLE
[ request] Please make a reverse convert to px

### ISSUE THREAD

**Issue by anephew** [IanLew/px2rem#2]
Hello!

Useful expansion, there was not enough time to do the same, but you did )

But very much needed also reverse conversion to px. For example by <kbd>Ctrl+`</kbd>

Thank you!

**Comment by IanLew** [comment]
I'm sorry, I'll do it when I'm free, It takes time for me to read English documents. By the way, The buttons are my personal custom, but they don't seem to fit the public taste. Wait for the good news :)
