### ISSUE TITLE
[ request] Remove px2rem from the main menu

### ISSUE THREAD

**Issue by anephew** [IanLew/px2rem#3]
Hello!

It would be nice to remove px2rem from the main menu and move to Edit (where other settings of the extensions). This setting is not often needed, It is better not to overload the main menu for such a small function =)

![image](https://user-images.githubusercontent.com/551514/42004804-285f9ac2-7a7a-11e8-98c9-900c09d98254.png)

Thank you!

**Comment by IanLew** [comment]
Well, then there's something new, please wait.
